// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	domain "chat-apps/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MessageRepository is an autogenerated mock type for the MessageRepository type
type MessageRepository struct {
	mock.Mock
}

// CreateMessage provides a mock function with given fields: message
func (_m *MessageRepository) CreateMessage(message domain.Message) (domain.Message, error) {
	ret := _m.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for CreateMessage")
	}

	var r0 domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.Message) (domain.Message, error)); ok {
		return rf(message)
	}
	if rf, ok := ret.Get(0).(func(domain.Message) domain.Message); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Get(0).(domain.Message)
	}

	if rf, ok := ret.Get(1).(func(domain.Message) error); ok {
		r1 = rf(message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMessagesByConversationID provides a mock function with given fields: conversationID
func (_m *MessageRepository) GetMessagesByConversationID(conversationID int) ([]domain.Message, error) {
	ret := _m.Called(conversationID)

	if len(ret) == 0 {
		panic("no return value specified for GetMessagesByConversationID")
	}

	var r0 []domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]domain.Message, error)); ok {
		return rf(conversationID)
	}
	if rf, ok := ret.Get(0).(func(int) []domain.Message); ok {
		r0 = rf(conversationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(conversationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMessageRepository creates a new instance of MessageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageRepository {
	mock := &MessageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
