// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	domain "chat-apps/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NotificationService is an autogenerated mock type for the NotificationService type
type NotificationService struct {
	mock.Mock
}

// GetNotificationsByUserID provides a mock function with given fields: userID
func (_m *NotificationService) GetNotificationsByUserID(userID int) ([]domain.Notification, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetNotificationsByUserID")
	}

	var r0 []domain.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]domain.Notification, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(int) []domain.Notification); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendNotification provides a mock function with given fields: userID, message
func (_m *NotificationService) SendNotification(userID int, message string) (domain.Notification, error) {
	ret := _m.Called(userID, message)

	if len(ret) == 0 {
		panic("no return value specified for SendNotification")
	}

	var r0 domain.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(int, string) (domain.Notification, error)); ok {
		return rf(userID, message)
	}
	if rf, ok := ret.Get(0).(func(int, string) domain.Notification); ok {
		r0 = rf(userID, message)
	} else {
		r0 = ret.Get(0).(domain.Notification)
	}

	if rf, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = rf(userID, message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewNotificationService creates a new instance of NotificationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationService {
	mock := &NotificationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
