openapi: 3.0.0
info:
  title: Chat Application API
  description: API documentation for the Chat Application
  version: 1.0.0
servers:
  - url: http://localhost:8080

tags:
  - name: Users
    description: Endpoints related to user management
  - name: Notifications
    description: Endpoints related to notifications
  - name: Messages
    description: Endpoints related to messages
  - name: Jobs
    description: Endpoints related to background jobs
  - name: Files
    description: Endpoints related to file management
  - name: Conversations
    description: Endpoints related to conversations
  - name: Articles
    description: Endpoints related to articles

paths:
  /users:
    post:
      tags:
        - Users
      summary: Create a new user
      requestBody:
        description: User to be created
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - username
                - email
                - password
      responses:
        '200':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  username:
                    type: string
                  email:
                    type: string
                  password:
                    type: string
                  created_at:
                    type: string
                    format: date-time
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /users/{id}:
    get:
      tags:
        - Users
      summary: Get user by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  username:
                    type: string
                  email:
                    type: string
                  password:
                    type: string
                  created_at:
                    type: string
                    format: date-time
        '400':
          description: Invalid user ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /notifications:
    post:
      tags:
        - Notifications
      summary: Send a notification to a user
      requestBody:
        description: Notification details
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                message:
                  type: string
              required:
                - user_id
                - message
      responses:
        '200':
          description: Notification sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  user_id:
                    type: integer
                  message:
                    type: string
                  sent_at:
                    type: string
                    format: date-time
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /notifications/{userId}:
    get:
      tags:
        - Notifications
      summary: Get all notifications for a specific user
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Notifications found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    user_id:
                      type: integer
                    message:
                      type: string
                    sent_at:
                      type: string
                      format: date-time
        '400':
          description: Invalid user ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /messages/{conversationId}:
    post:
      tags:
        - Messages
      summary: Create a new message in a conversation
      requestBody:
        description: Message details
        content:
          application/json:
            schema:
              type: object
              properties:
                sender_id:
                  type: integer
                content:
                  type: string
              required:
                - sender_id
                - content
      responses:
        '200':
          description: Message created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  conversation_id:
                    type: integer
                  sender_id:
                    type: integer
                  content:
                    type: string
                  created_at:
                    type: string
                    format: date-time
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

    get:
      tags:
        - Messages
      summary: Get all messages for a conversation
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Messages found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    conversation_id:
                      type: integer
                    sender_id:
                      type: integer
                    content:
                      type: string
                    created_at:
                      type: string
                      format: date-time
        '400':
          description: Invalid conversation ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /notifications/broadcast:
    post:
      tags:
        - Jobs
      summary: Queue a broadcast notification job
      requestBody:
        description: Broadcast notification details
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
              required:
                - message
      responses:
        '200':
          description: Job queued successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_id:
                    type: integer
                  status:
                    type: string
                  queued_at:
                    type: string
                    format: date-time
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /jobs/{id}:
    get:
      tags:
        - Jobs
      summary: Get the status of a job
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Job status found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  status:
                    type: string
                  completed_at:
                    type: string
                    format: date-time
        '400':
          description: Invalid job ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /files/upload:
    post:
      tags:
        - Files
      summary: Upload a file
      requestBody:
        description: File upload details
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                file:
                  type: string
              required:
                - user_id
                - file
      responses:
        '200':
          description: File uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  user_id:
                    type: integer
                  file_url:
                    type: string
                  uploaded_at:
                    type: string
                    format: date-time
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /files/{id}:
    get:
      tags:
        - Files
      summary: Get file by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: File found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  user_id:
                    type: integer
                  file_url:
                    type: string
                  uploaded_at:
                    type: string
                    format: date-time
        '400':
          description: Invalid file ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /conversations:
    post:
      tags:
        - Conversations
      summary: Create a new conversation
      requestBody:
        description: Conversation details
        content:
          application/json:
            schema:
              type: object
              properties:
                participants:
                  type: array
                  items:
                    type: integer
              required:
                - participants
      responses:
        '200':
          description: Conversation created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  participants:
                    type: array
                    items:
                      type: integer
                  created_at:
                    type: string
                    format: date-time
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /conversations/{conversationId}:
    get:
      tags:
        - Conversations
      summary: Get conversation by ID
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Conversation found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  participants:
                    type: array
                    items:
                      type: integer
                  created_at:
                    type: string
                    format: date-time
        '400':
          description: Invalid conversation ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Conversation not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /article-list:
    get:
      tags:
        - Articles
      summary: Get list articles
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Articles found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    menu:
                      type: string
                    sub_menu:
                      type: string
                    title:
                      type: string
                    image:
                      type: string
                    time_ago:
                      type: string
                    likes:
                      type: integer
                    comment_count:
                      type: integer
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

